name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
          package-manager: bun
      - name: Install dependencies
        run: bun install --no-frozen-lockfile
        with:
          path: ./docs
          bun-version: 1.1.27
          package-manager: bun

      - name: Deploy to GitHub Pages with Astro
        uses: withastro/action@v3
        with:
          path: ./docs
          bun-version: 1.1.27
          package-manager: bun

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
